'see license.txt For source licenses
Strict

Import spine

Const SPINE_MAX_FLOAT:= 999999999.0
Const SPINE_MIN_FLOAT:= -999999999.0

Const SPINE_PRECISION_ENTITY_BOUNDS:= 0
Const SPINE_PRECISION_ATTACHMENT_BOUNDS:= 1
Const SPINE_PRECISION_ATTACHMENT_HULL:= 2